// ── The gifs, baked ──────────────────────────────────────────────────────────
// The two verdicts and the route's error page each have a gif — the archive
// on a run the archive cannot answer for is MADE of it (world/kaleidoscope.js,
// the rings on an edge run), and the verdict is read over it, tiled
// (components/error/Tiles.svelte). A gif cannot be a texture: three uploads
// one frame of an <img>, and drawImage of one draws the first. So every gif
// in static/gifs is baked here into a SHEET: every frame, scaled to CELL wide,
// in a grid, one JPEG beside it, and src/lib/data/gifs.js says how each sheet
// is cut — columns, rows, frames, the cell, the frame rate. A gif whose
// frames will not fit a 4096-square sheet keeps every second (third, ...)
// frame, at that fraction of its rate.
//
//   node scripts/gifs.mjs        bakes every gif in static/gifs
//   CELL=240                     the cell width (default 240)
//
// Decoded by Chromium's ImageDecoder (WebCodecs) on the lane's own browser
// (lane.mjs), which is the one thing here that can read every frame of a gif.
import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { launch } from './lane.mjs';

const DIR = 'static/gifs';
const OUT = 'src/lib/data/gifs.js';
const CELL = Number(process.env.CELL ?? 240);
const MAX = 4096;
const names = fs
	.readdirSync(DIR)
	.filter((f) => f.endsWith('.gif'))
	.map((f) => f.slice(0, -4))
	.sort();

const { browser } = await launch('webgl');
const page = await browser.newPage();
// The gifs are served to the page off the disk, on a localhost origin of the
// script's own (nothing listens on the port; the route answers before the
// network): ImageDecoder is only there in a secure context, which localhost
// is and about:blank is not.
const ORIGIN = 'http://localhost:9';
await page.route(`${ORIGIN}/**`, (route) => {
	const file = decodeURIComponent(new URL(route.request().url()).pathname.slice(1));
	if (!file)
		return route.fulfill({ contentType: 'text/html', body: '<!doctype html><title>gifs</title>' });
	route.fulfill({ path: path.join(DIR, file), contentType: 'image/gif' });
});
await page.goto(`${ORIGIN}/`);

const meta = {};
for (const name of names) {
	const r = await page.evaluate(
		async ({ name, CELL, MAX }) => {
			const res = await fetch(`/${name}.gif`);
			const dec = new ImageDecoder({ data: res.body, type: 'image/gif' });
			await dec.tracks.ready;
			await dec.completed;
			const n = dec.tracks.selectedTrack.frameCount;
			const f0 = await dec.decode({ frameIndex: 0 });
			const W = f0.image.displayWidth;
			const H = f0.image.displayHeight;
			f0.image.close();
			const w = CELL;
			const h = Math.round(((H / W) * CELL) / 2) * 2;
			// The grid: about square, inside MAX; every stride-th frame if not.
			let stride = 0;
			let frames, cols, rows;
			do {
				stride++;
				frames = Math.ceil(n / stride);
				cols = Math.max(1, Math.ceil(Math.sqrt((frames * h) / w)));
				rows = Math.ceil(frames / cols);
			} while (cols * w > MAX || rows * h > MAX);
			const canvas = document.createElement('canvas');
			canvas.width = cols * w;
			canvas.height = rows * h;
			const ctx = canvas.getContext('2d');
			ctx.imageSmoothingQuality = 'high';
			const durations = [];
			for (let k = 0; k < frames; k++) {
				const f = await dec.decode({ frameIndex: k * stride });
				durations.push(f.image.duration || 100000);
				ctx.drawImage(f.image, (k % cols) * w, Math.floor(k / cols) * h, w, h);
				f.image.close();
			}
			durations.sort((a, b) => a - b);
			const median = durations[Math.floor(durations.length / 2)];
			const fps = Math.round((1e6 / median / stride) * 100) / 100;
			return {
				dataUrl: canvas.toDataURL('image/jpeg', 0.86),
				n,
				stride,
				frames,
				cols,
				rows,
				w,
				h,
				fps,
				W,
				H
			};
		},
		{ name, CELL, MAX }
	);
	const { dataUrl, ...m } = r;
	const buf = Buffer.from(dataUrl.slice(dataUrl.indexOf(',') + 1), 'base64');
	fs.writeFileSync(path.join(DIR, `${name}.jpg`), buf);
	meta[name] = {
		src: `/gifs/${name}.jpg`,
		cols: m.cols,
		rows: m.rows,
		frames: m.frames,
		w: m.w,
		h: m.h,
		fps: m.fps
	};
	console.log(
		`${name}: ${m.W}x${m.H}, ${m.n} frames -> ${m.frames} (every ${m.stride}) at ${m.w}x${m.h} in ${m.cols}x${m.rows}, ${m.fps} fps, ${(buf.length / 1024).toFixed(0)} KB`
	);
}
await browser.close();

const lines = Object.entries(meta).map(
	([k, m]) =>
		`\t'${k}': { src: '${m.src}', cols: ${m.cols}, rows: ${m.rows}, frames: ${m.frames}, w: ${m.w}, h: ${m.h}, fps: ${m.fps} }`
);
fs.writeFileSync(
	OUT,
	`// GENERATED by scripts/gifs.mjs — do not edit. How each gif's sheet in
// static/gifs is cut: \`cols\` × \`rows\` cells of \`w\` × \`h\`, \`frames\` of them
// in reading order, at \`fps\`. See the script for what a sheet is.
export const GIFS = {
${lines.join(',\n')}
};
`
);
execSync(`npx prettier --write ${OUT}`, { stdio: 'ignore' });
console.log(`wrote ${OUT}`);
